version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb+srv://asdfqqqwsf12311:wCt4FPqwTYCBWK1h@test.mzaii9g.mongodb.net/?retryWrites=true&w=majority&appName=test

volumes:
  mongo-data:
